libdoip: doip::DoIPMessage Class Reference
doip::DoIPMessage Class Reference
Represents a complete DoIP message with internal ByteArray representation.
#include <DoIPMessage.h>
Public Member Functions
DoIPMessage ()
Default constructor - creates invalid empty message.
DoIPMessage (DoIPPayloadType payloadType, const ByteArray &payload)
Constructs a DoIP message with payload type and data.
DoIPMessage (DoIPPayloadType payloadType, ByteArray &&payload)
Constructs a DoIP message with payload type and data (move semantics).
DoIPMessage (DoIPPayloadType payloadType, std::initializer_list< uint8_t > init_list)
Constructs a DoIP message with payload type and initializer list.
DoIPMessage (DoIPPayloadType payloadType, const uint8_t *data, size_t size)
Constructs a DoIP message from raw byte array.
template<typename Iterator >
DoIPMessage (DoIPPayloadType payloadType, Iterator first, Iterator last)
Constructs a DoIP message from iterator range.
DoIPPayloadType getPayloadType () const
Gets the payload type of this message.
ByteArrayRef getPayload () const
Gets the payload data (without header).
ByteArrayRef getDiagnosticMessagePayload () const
Gets the payload data (without header).
size_t getPayloadSize () const
Gets the payload size in bytes (without header).
size_t getMessageSize () const
Get the complete message size (header + payload).
ByteArrayRef getData () const
Gets direct access to the complete message data for sending.
const uint8_t * data () const
Gets direct pointer to the message data (for legacy APIs).
size_t size () const
Gets the size for use with legacy APIs.
const ByteArray & asByteArray () const
Get the complete message as ByteArray.
ByteArray copyAsByteArray () const
Get a copy of the complete message as ByteArray.
bool hasSourceAddress () const
Check if the message has a Source Address field.
std::optional< DoIPAddress > getSourceAddress () const
Get the Source Address of the message (if message is a Diagnostic Message).
std::optional< DoIPAddress > getLogicalAddress () const
Get the Logical Address of the message (if message is a Vehicle Identification Response).
std::optional< DoIPAddress > getTargetAddress () const
Get the Target Address of the message (if message is a Diagnostic Message).
std::optional< DoIpVin > getVin () const
Get the vehicle identification number (VIN) if message is a Vehicle Identification Response.
std::optional< DoIpEid > getEid () const
Get the entity id (EID) if message is a Vehicle Identification Response.
std::optional< DoIpGid > getGid () const
Get the group id (GID) if message is a Vehicle Identification Response.
std::optional< DoIPFurtherAction > getFurtherActionRequest () const
Get the Further Action Request object if message is a Vehicle Identification Response.
bool isValid () const
Checks if the message is valid.
Static Public Member Functions
static bool isValidProtocolVersion (const uint8_t *data, size_t length, size_t offset=0)
Checks if the protocol version is valid.
static std::optional< std::pair< DoIPPayloadType, uint32_t > > tryParseHeader (const uint8_t *data, size_t length)
Gets the payload type from raw data.
static std::optional< DoIPMessage > tryParse (const uint8_t *data, size_t length)
Parse a DoIP message from raw data.
Protected Member Functions
void buildMessage (DoIPPayloadType payloadType, const ByteArray &payload)
Builds the internal message representation.
bool isValidProtocolVersion () const
Checks if the protocol version is valid.
uint32_t getPayloadLengthFromHeader () const
Gets the payload length from the header.
Protected Attributes
ByteArray m_data
Complete message data (header + payload)
Detailed Description
Represents a complete DoIP message with internal ByteArray representation.
The message is stored internally as a complete ByteArray including the 8-byte header and payload. This eliminates the need for copying when sending messages.
Memory layout: [0] Protocol Version [1] Inverse Protocol Version [2-3] Payload Type (big-endian uint16_t) [4-7] Payload Length (big-endian uint32_t) [8...] Payload data
The message types are listed in table 17.
Definition at line 82 of file DoIPMessage.h.
Constructor & Destructor Documentation
DoIPMessage() [1/6]
doip::DoIPMessage::DoIPMessage () inline
Default constructor - creates invalid empty message.
Definition at line 88 of file DoIPMessage.h.
DoIPMessage() [2/6]
doip::DoIPMessage::DoIPMessage (DoIPPayloadType payloadType, const ByteArray & payload) inline explicit
Constructs a DoIP message with payload type and data.
Parameters
payloadType The payload type for this message
payload The payload data as a vector of bytes
Definition at line 96 of file DoIPMessage.h.
References buildMessage().
DoIPMessage() [3/6]
doip::DoIPMessage::DoIPMessage (DoIPPayloadType payloadType, ByteArray && payload) inline explicit
Constructs a DoIP message with payload type and data (move semantics).
Parameters
payloadType The payload type for this message
payload The payload data as a vector of bytes (moved)
Definition at line 106 of file DoIPMessage.h.
References buildMessage().
DoIPMessage() [4/6]
doip::DoIPMessage::DoIPMessage (DoIPPayloadType payloadType, std::initializer_list< uint8_t > init_list) inline
Constructs a DoIP message with payload type and initializer list.
Parameters
payloadType The payload type for this message
init_list Initializer list of bytes for the payload
Definition at line 116 of file DoIPMessage.h.
References buildMessage().
DoIPMessage() [5/6]
doip::DoIPMessage::DoIPMessage (DoIPPayloadType payloadType, const uint8_t * data, size_t size) inline explicit
Constructs a DoIP message from raw byte array.
Parameters
payloadType The payload type for this message
data Pointer to raw payload byte data
size Number of bytes to copy from payload data
Definition at line 128 of file DoIPMessage.h.
References buildMessage(), data(), and size().
DoIPMessage() [6/6]
template<typename Iterator > doip::DoIPMessage::DoIPMessage (DoIPPayloadType payloadType, Iterator first, Iterator last) inline explicit
Constructs a DoIP message from iterator range.
Template Parameters
Iterator Input iterator type
Parameters
payloadType The payload type for this message
first Iterator to the beginning of the data range
last Iterator to the end of the data range
Definition at line 142 of file DoIPMessage.h.
References buildMessage().
Member Function Documentation
asByteArray()
const ByteArray& doip::DoIPMessage::asByteArray () const inline
Get the complete message as ByteArray.
Returns
const ByteArray& Reference to the complete message data
Definition at line 240 of file DoIPMessage.h.
References m_data.
buildMessage()
void doip::DoIPMessage::buildMessage (DoIPPayloadType payloadType, const ByteArray & payload) inline protected
Builds the internal message representation.
Parameters
payloadType The payload type
payload The payload data
Definition at line 452 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, m_data, doip::PROTOCOL_VERSION, doip::PROTOCOL_VERSION_INV, doip::ByteArray::writeEnum(), and doip::ByteArray::writeU32BE().
Referenced by DoIPMessage().
copyAsByteArray()
ByteArray doip::DoIPMessage::copyAsByteArray () const inline
Get a copy of the complete message as ByteArray.
Returns
ByteArray A copy of the complete message data
Definition at line 249 of file DoIPMessage.h.
References m_data.
data()
const uint8_t* doip::DoIPMessage::data () const inline
Gets direct pointer to the message data (for legacy APIs).
Returns
const uint8_t* Pointer to the message data
Definition at line 222 of file DoIPMessage.h.
References m_data.
Referenced by DoIPMessage(), isValidProtocolVersion(), doip::DoIPClient::sendAliveCheckResponse(), doip::DoIPClient::sendDiagnosticMessage(), doip::DoIPConnection::sendProtocolMessage(), doip::DoIPClient::sendRoutingActivationRequest(), doip::DoIPClient::sendVehicleIdentificationRequest(), tryParse(), and tryParseHeader().
getData()
ByteArrayRef doip::DoIPMessage::getData () const inline
Gets direct access to the complete message data for sending.
This method returns a pointer and size without copying, making it efficient for network transmission.
Returns
ByteArrayRef Reference to the complete message (header + payload)
Definition at line 213 of file DoIPMessage.h.
References m_data.
getDiagnosticMessagePayload()
ByteArrayRef doip::DoIPMessage::getDiagnosticMessagePayload () const inline
Gets the payload data (without header).
Returns
ByteArrayRef pointing to the payload portion
Definition at line 177 of file DoIPMessage.h.
References doip::DOIP_DIAG_HEADER_SIZE, and m_data.
Referenced by doip::operator<<().
getEid()
std::optional<DoIpEid> doip::DoIPMessage::getEid () const inline
Get the entity id (EID) if message is a Vehicle Identification Response.
Returns
std::optional<DoIPAddress> The VIN if present, std::nullopt otherwise
Definition at line 327 of file DoIPMessage.h.
References getPayload(), getPayloadType(), and doip::VehicleIdentificationResponse.
getFurtherActionRequest()
std::optional<DoIPFurtherAction> doip::DoIPMessage::getFurtherActionRequest () const inline
Get the Further Action Request object if message is a Vehicle Identification Response.
Returns
std::optional<DoIPFurtherAction> The Further Action Request if present, std::nullopt otherwise
Definition at line 353 of file DoIPMessage.h.
References getPayload(), getPayloadType(), and doip::VehicleIdentificationResponse.
getGid()
std::optional<DoIpGid> doip::DoIPMessage::getGid () const inline
Get the group id (GID) if message is a Vehicle Identification Response.
Returns
std::optional<DoIPAddress> The VIN if present, std::nullopt otherwise
Definition at line 340 of file DoIPMessage.h.
References getPayload(), getPayloadType(), and doip::VehicleIdentificationResponse.
getLogicalAddress()
std::optional<DoIPAddress> doip::DoIPMessage::getLogicalAddress () const inline
Get the Logical Address of the message (if message is a Vehicle Identification Response).
Returns
std::optional<DoIPAddress> The logical address if present, std::nullopt otherwise
Definition at line 288 of file DoIPMessage.h.
References getPayload(), getPayloadType(), doip::readAddressFrom(), and doip::VehicleIdentificationResponse.
getMessageSize()
size_t doip::DoIPMessage::getMessageSize () const inline
Get the complete message size (header + payload).
Returns
size_t Total number of bytes
Definition at line 201 of file DoIPMessage.h.
References m_data.
getPayload()
ByteArrayRef doip::DoIPMessage::getPayload () const inline
Gets the payload data (without header).
Returns
ByteArrayRef pointing to the payload portion
Definition at line 165 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, and m_data.
Referenced by getEid(), getFurtherActionRequest(), getGid(), getLogicalAddress(), getSourceAddress(), getTargetAddress(), getVin(), hasSourceAddress(), and doip::operator<<().
getPayloadLengthFromHeader()
uint32_t doip::DoIPMessage::getPayloadLengthFromHeader () const inline protected
Gets the payload length from the header.
Returns
size_t The payload length stored in the header
Definition at line 491 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, m_data, and doip::ByteArray::readU32BE().
Referenced by isValid().
getPayloadSize()
size_t doip::DoIPMessage::getPayloadSize () const inline
Gets the payload size in bytes (without header).
Returns
size_t Number of bytes in the payload
Definition at line 189 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, and m_data.
Referenced by isValid(), and doip::operator<<().
getPayloadType()
DoIPPayloadType doip::DoIPMessage::getPayloadType () const inline
Gets the payload type of this message.
Returns
The DoIP payload type
Definition at line 152 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, m_data, and doip::NegativeAck.
Referenced by getEid(), getFurtherActionRequest(), getGid(), getLogicalAddress(), getTargetAddress(), getVin(), hasSourceAddress(), doip::operator<<(), and doip::DoIPClient::receiveVehicleAnnouncement().
getSourceAddress()
std::optional<DoIPAddress> doip::DoIPMessage::getSourceAddress () const inline
Get the Source Address of the message (if message is a Diagnostic Message).
Returns
std::optional<DoIPAddress> The source address if present, std::nullopt otherwise
Definition at line 274 of file DoIPMessage.h.
References getPayload(), hasSourceAddress(), and doip::readAddressFrom().
Referenced by doip::message::makeRoutingActivationResponse(), and doip::operator<<().
getTargetAddress()
std::optional<DoIPAddress> doip::DoIPMessage::getTargetAddress () const inline
Get the Target Address of the message (if message is a Diagnostic Message).
Returns
std::optional<DoIPAddress> The target address if present, std::nullopt otherwise
Definition at line 301 of file DoIPMessage.h.
References doip::DiagnosticMessage, getPayload(), getPayloadType(), and doip::readAddressFrom().
Referenced by doip::operator<<().
getVin()
std::optional<DoIpVin> doip::DoIPMessage::getVin () const inline
Get the vehicle identification number (VIN) if message is a Vehicle Identification Response.
Returns
std::optional<DoIPAddress> The VIN if present, std::nullopt otherwise
Definition at line 314 of file DoIPMessage.h.
References getPayload(), getPayloadType(), and doip::VehicleIdentificationResponse.
hasSourceAddress()
bool doip::DoIPMessage::hasSourceAddress () const inline
Check if the message has a Source Address field.
Returns
Returns true in the case of success, false otherwise.
Definition at line 258 of file DoIPMessage.h.
References doip::AliveCheckResponse, doip::DiagnosticMessage, getPayload(), getPayloadType(), doip::RoutingActivationRequest, and doip::RoutingActivationResponse.
Referenced by getSourceAddress().
isValid()
bool doip::DoIPMessage::isValid () const inline
Checks if the message is valid.
Returns
bool True if the message has a valid structure
Definition at line 366 of file DoIPMessage.h.
References doip::DOIP_HEADER_SIZE, getPayloadLengthFromHeader(), getPayloadSize(), isValidProtocolVersion(), and m_data.
isValidProtocolVersion() [1/2]
bool doip::DoIPMessage::isValidProtocolVersion () const inline protected
Checks if the protocol version is valid.
Returns
bool True if valid
Definition at line 476 of file DoIPMessage.h.
References doip::ISO_13400_2010, doip::ISO_13400_2025, and m_data.
Referenced by isValid(), and tryParseHeader().
isValidProtocolVersion() [2/2]
static bool doip::DoIPMessage::isValidProtocolVersion (const uint8_t * data, size_t length, size_t offset = 0) inline static
Checks if the protocol version is valid.
Parameters
data Pointer to the byte array
length Length of the data
offset Offset to start checking from (default: 0)
Returns
bool True if valid
Definition at line 379 of file DoIPMessage.h.
References data(), doip::ISO_13400_2010, and doip::ISO_13400_2025.
size()
size_t doip::DoIPMessage::size () const inline
Gets the size for use with legacy APIs.
Returns
size_t Size of the complete message
Definition at line 231 of file DoIPMessage.h.
References m_data.
Referenced by DoIPMessage(), doip::DoIPClient::sendAliveCheckResponse(), doip::DoIPClient::sendDiagnosticMessage(), doip::DoIPConnection::sendProtocolMessage(), doip::DoIPDefaultConnection::sendProtocolMessage(), doip::DoIPClient::sendRoutingActivationRequest(), and doip::DoIPClient::sendVehicleIdentificationRequest().
tryParse()
static std::optional<DoIPMessage> doip::DoIPMessage::tryParse (const uint8_t * data, size_t length) inline static
Parse a DoIP message from raw data.
Parameters
data Pointer to raw message data
length Length of the data
Returns
std::optional<DoIPMessage> The parsed message or std::nullopt if invalid
Definition at line 425 of file DoIPMessage.h.
References data(), doip::DOIP_HEADER_SIZE, m_data, and tryParseHeader().
Referenced by doip::DoIPClient::receiveMessage(), doip::DoIPClient::receiveUdpMessage(), and doip::DoIPClient::receiveVehicleAnnouncement().
tryParseHeader()
static std::optional<std::pair<DoIPPayloadType, uint32_t> > doip::DoIPMessage::tryParseHeader (const uint8_t * data, size_t length) inline static
Gets the payload type from raw data.
Parameters
data Pointer to the byte array
length Length of the data
Returns
std::optional<DoIPPayloadType> The payload type if valid
Definition at line 399 of file DoIPMessage.h.
References data(), doip::DOIP_HEADER_SIZE, isValidProtocolVersion(), doip::util::readU32BE(), and doip::toPayloadType().
Referenced by doip::DoIPConnection::receiveTcpMessage(), and tryParse().
Member Data Documentation
m_data
ByteArray doip::DoIPMessage::m_data protected
Complete message data (header + payload)
Definition at line 444 of file DoIPMessage.h.
Referenced by asByteArray(), buildMessage(), copyAsByteArray(), data(), getData(), getDiagnosticMessagePayload(), getMessageSize(), getPayload(), getPayloadLengthFromHeader(), getPayloadSize(), getPayloadType(), isValid(), isValidProtocolVersion(), size(), and tryParse().
The documentation for this class was generated from the following file:
inc/DoIPMessage.h