libdoip: doip::uds::UdsMock Class Reference
doip::uds::UdsMock Class Reference
#include <UdsMock.h>
Public Member Functions
UdsMock ()=default
void registerService (UdsService serviceId, IUdsServiceHandlerPtr handler)
void registerService (UdsService serviceId, std::function< UdsResponse(const ByteArray &)> fn)
void unregisterService (UdsService serviceId)
void clear ()
void registerDiagnosticSessionControlHandler (std::function< UdsResponse(uint8_t sessionType)> handler)
void registerECUResetHandler (std::function< UdsResponse(uint8_t resetType)> handler)
void registerReadDataByIdentifierHandler (std::function< UdsResponse(uint16_t did)> handler)
void registerWriteDataByIdentifierHandler (std::function< UdsResponse(uint16_t did, ByteArray value)> handler)
void registerTesterPresentHandler (std::function< UdsResponse(uint8_t subFunction)> handler)
ByteArray handleDiagnosticRequest (const ByteArray &request) const
void registerDefaultServices ()
Detailed Description
Definition at line 21 of file UdsMock.h.
Constructor & Destructor Documentation
UdsMock()
doip::uds::UdsMock::UdsMock () default
Member Function Documentation
clear()
void doip::uds::UdsMock::clear () inline
Definition at line 41 of file UdsMock.h.
handleDiagnosticRequest()
ByteArray doip::uds::UdsMock::handleDiagnosticRequest (const ByteArray & request) const
Definition at line 6 of file UdsMock.cpp.
References doip::uds::findServiceDescriptor(), doip::uds::GeneralProgrammingFailure, doip::uds::IncorrectMessageLengthOrInvalidFormat, doip::uds::UdsServiceDescriptor::maxReqLength, doip::uds::UdsServiceDescriptor::maxRspLength, doip::uds::UdsServiceDescriptor::minReqLength, doip::uds::UdsServiceDescriptor::minRspLength, and doip::uds::ServiceNotSupported.
registerDefaultServices()
void doip::uds::UdsMock::registerDefaultServices () inline
Definition at line 65 of file UdsMock.h.
References doip::uds::AccessTimingParameters, doip::uds::ClearDiagnosticInformation, doip::uds::CommunicationControl, doip::uds::ControlDTCSetting, doip::uds::DiagnosticSessionControl, doip::uds::DynamicallyDefineDataIdentifier, doip::uds::ECUReset, doip::uds::LinkControl, doip::uds::ReadDataByIdentifier, doip::uds::ReadDataByPeriodicIdentifier, doip::uds::ReadDTCInformation, doip::uds::ReadMemoryByAddress, doip::uds::ReadScalingDataByIdentifier, registerService(), doip::uds::ResponseOnEvent, doip::uds::SecuredDataTransmission, doip::uds::SecurityAccess, doip::uds::ServiceNotSupported, doip::uds::TesterPresent, doip::uds::WriteDataByIdentifier, and doip::uds::WriteMemoryByAddress.
registerDiagnosticSessionControlHandler()
void doip::uds::UdsMock::registerDiagnosticSessionControlHandler (std::function< UdsResponse(uint8_t sessionType)> handler)
Definition at line 43 of file UdsMock.cpp.
References doip::uds::DiagnosticSessionControl, and registerService().
registerECUResetHandler()
void doip::uds::UdsMock::registerECUResetHandler (std::function< UdsResponse(uint8_t resetType)> handler)
Definition at line 50 of file UdsMock.cpp.
References doip::uds::ECUReset, and registerService().
registerReadDataByIdentifierHandler()
void doip::uds::UdsMock::registerReadDataByIdentifierHandler (std::function< UdsResponse(uint16_t did)> handler)
Definition at line 57 of file UdsMock.cpp.
References doip::uds::ReadDataByIdentifier, and registerService().
registerService() [1/2]
void doip::uds::UdsMock::registerService (UdsService serviceId, IUdsServiceHandlerPtr handler) inline
Definition at line 26 of file UdsMock.h.
Referenced by registerDefaultServices(), registerDiagnosticSessionControlHandler(), registerECUResetHandler(), registerReadDataByIdentifierHandler(), registerTesterPresentHandler(), and registerWriteDataByIdentifierHandler().
registerService() [2/2]
void doip::uds::UdsMock::registerService (UdsService serviceId, std::function< UdsResponse(const ByteArray &)> fn) inline
Definition at line 31 of file UdsMock.h.
registerTesterPresentHandler()
void doip::uds::UdsMock::registerTesterPresentHandler (std::function< UdsResponse(uint8_t subFunction)> handler)
Definition at line 71 of file UdsMock.cpp.
References registerService(), and doip::uds::TesterPresent.
registerWriteDataByIdentifierHandler()
void doip::uds::UdsMock::registerWriteDataByIdentifierHandler (std::function< UdsResponse(uint16_t did, ByteArray value)> handler)
Definition at line 64 of file UdsMock.cpp.
References registerService(), and doip::uds::WriteDataByIdentifier.
unregisterService()
void doip::uds::UdsMock::unregisterService (UdsService serviceId) inline
Definition at line 36 of file UdsMock.h.
The documentation for this class was generated from the following files:
inc/uds/UdsMock.h
src/uds/UdsMock.cpp