libdoip: doip::Logger Class Reference
doip::Logger Class Reference
Centralized logger for the DoIP library.
#include <Logger.h>
Static Public Member Functions
static std::shared_ptr< spdlog::logger > get (const std::string &name="doip", spdlog::level::level_enum level=spdlog::level::info)
static std::shared_ptr< spdlog::logger > getUdp ()
static std::shared_ptr< spdlog::logger > getTcp ()
static void setLevel (spdlog::level::level_enum level)
static void setPattern (const std::string &pattern)
static bool colorsSupported ()
Detailed Description
Centralized logger for the DoIP library.
Definition at line 70 of file Logger.h.
Member Function Documentation
colorsSupported()
static bool doip::Logger::colorsSupported () inline static
Definition at line 103 of file Logger.h.
Referenced by doip::DoIPClient::printVehicleInformationResponse().
get()
static std::shared_ptr<spdlog::logger> doip::Logger::get (const std::string & name = "doip", spdlog::level::level_enum level = spdlog::level::info) inline static
Definition at line 72 of file Logger.h.
References doip::DEFAULT_PATTERN.
Referenced by getTcp(), getUdp(), setLevel(), and setPattern().
getTcp()
static std::shared_ptr<spdlog::logger> doip::Logger::getTcp () inline static
Definition at line 91 of file Logger.h.
References get().
getUdp()
static std::shared_ptr<spdlog::logger> doip::Logger::getUdp () inline static
Definition at line 87 of file Logger.h.
References get().
setLevel()
static void doip::Logger::setLevel (spdlog::level::level_enum level) inline static
Definition at line 95 of file Logger.h.
References get().
setPattern()
static void doip::Logger::setPattern (const std::string & pattern) inline static
Definition at line 99 of file Logger.h.
References get().
The documentation for this class was generated from the following files:
inc/Logger.h
src/Logger.cpp