libdoip: doip::DoIPConnection Class Reference
doip::DoIPConnection Class Reference
#include <DoIPConnection.h>
Public Member Functions
DoIPConnection (int tcpSocket, UniqueServerModelPtr model)
int receiveTcpMessage ()
size_t receiveFixedNumberOfBytesFromTCP (uint8_t *receivedData, size_t payloadLength)
Receive exactly payloadLength bytes from the TCP stream and put them into receivedData.
void sendDiagnosticPayload (const DoIPAddress &sourceAddress, const ByteArray &payload)
bool isSocketActive ()
void triggerDisconnection ()
void sendDiagnosticAck (const DoIPAddress &sourceAddress)
void sendDiagnosticNegativeAck (const DoIPAddress &sourceAddress, DoIPNegativeDiagnosticAck ackCode)
ssize_t sendProtocolMessage (const DoIPMessage &msg) override
Send a DoIP protocol message to the client.
void closeConnection (DoIPCloseReason reason) override
Close the TCP connection.
DoIPAddress getServerAddress () const override
Get the server's logical address.
DoIPAddress getClientAddress () const override
Get the currently client (active source) address.
void setClientAddress (const DoIPAddress &address) override
Set the client (active source) address after routing activation.
DoIPDiagnosticAck notifyDiagnosticMessage (const DoIPMessage &msg) override
Handle an incoming diagnostic message (application callback)
void notifyConnectionClosed (DoIPCloseReason reason) override
Notify application that connection is closing.
void notifyDiagnosticAckSent (DoIPDiagnosticAck ack) override
Notify application that diagnostic ACK/NACK was sent.
bool hasDownstreamHandler () const override
Check if downstream forwarding is available.
Public Member Functions inherited from doip::DoIPDefaultConnection
DoIPDefaultConnection (UniqueServerModelPtr model)
Constructs a DoIPDefaultConnection.
ssize_t sendProtocolMessage (const DoIPMessage &msg) override
Sends a DoIP protocol message to the client.
void closeConnection (DoIPCloseReason reason) override
Closes the connection.
bool isOpen () const override
Checks if the connection is open.
DoIPCloseReason getCloseReason () const override
Gets the reason for connection closure.
bool isRoutingActivated () const
Checks if routing is currently activated.
uint8_t getAliveCheckRetryCount () const
Gets the alive check retry count.
std::chrono::milliseconds getInitialInactivityTimeout () const
Gets the initial inactivity timeout duration.
std::chrono::milliseconds getGeneralInactivityTimeout () const
Gets the general inactivity timeout duration.
std::chrono::milliseconds getAliveCheckTimeout () const
Gets the alive check timeout duration.
std::chrono::milliseconds getDownstreamResponseTimeout () const
Gets the downstream response timeout duration.
void setAliveCheckRetryCount (uint8_t count)
Sets the alive check retry count.
void setInitialInactivityTimeout (std::chrono::milliseconds timeout)
Sets the initial inactivity timeout duration.
void setGeneralInactivityTimeout (std::chrono::milliseconds timeout)
Sets the general inactivity timeout duration.
void setAliveCheckTimeout (std::chrono::milliseconds timeout)
Sets the alive check timeout duration.
void setDownstreamResponseTimeout (std::chrono::milliseconds timeout)
Sets the downstream response timeout duration.
DoIPAddress getServerAddress () const override
Gets the server's logical address.
DoIPAddress getClientAddress () const override
Gets the client's address.
DoIPDiagnosticAck notifyDiagnosticMessage (const DoIPMessage &msg) override
Handles an incoming diagnostic message.
void notifyConnectionClosed (DoIPCloseReason reason) override
Notifies application that connection is closing.
void notifyDiagnosticAckSent (DoIPDiagnosticAck ack) override
Notifies application that diagnostic ACK/NACK was sent.
bool hasDownstreamHandler () const override
Checks if a downstream handler is present.
DoIPDownstreamResult notifyDownstreamRequest (const DoIPMessage &msg) override
Notifies application of a downstream request.
void receiveDownstreamResponse (const ByteArray &response, DoIPDownstreamResult result) override
Receives a downstream response.
DoIPServerState getState () const
Gets the current state of the connection.
UniqueServerModelPtr & getServerModel ()
Gets the server model.
void handleMessage2 (const DoIPMessage &message)
Handles a message (internal helper)
Public Member Functions inherited from doip::IConnectionContext
virtual ~IConnectionContext ()=default
Additional Inherited Members
Protected Member Functions inherited from doip::DoIPDefaultConnection
void transitionTo (DoIPServerState newState)
std::chrono::milliseconds getTimerDuration (StateDescriptor const *stateDesc)
void startStateTimer (StateDescriptor const *stateDesc)
void restartStateTimer ()
void handleSocketInitialized (DoIPServerEvent event, OptDoIPMessage msg)
void handleWaitRoutingActivation (DoIPServerEvent event, OptDoIPMessage msg)
void handleRoutingActivated (DoIPServerEvent event, OptDoIPMessage msg)
void handleWaitAliveCheckResponse (DoIPServerEvent event, OptDoIPMessage msg)
void handleWaitDownstreamResponse (DoIPServerEvent event, OptDoIPMessage msg)
void handleFinalize (DoIPServerEvent event, OptDoIPMessage msg)
void handleTimeout (ConnectionTimers timer_id)
Default timeout handler.
ssize_t sendRoutingActivationResponse (const DoIPAddress &source_address, DoIPRoutingActivationResult response_code)
ssize_t sendAliveCheckRequest ()
ssize_t sendDiagnosticMessageResponse (const DoIPAddress &sourceAddress, DoIPDiagnosticAck ack)
ssize_t sendDownstreamResponse (const DoIPAddress &sourceAddress, const ByteArray &payload)
Protected Attributes inherited from doip::DoIPDefaultConnection
UniqueServerModelPtr m_serverModel
std::array< StateDescriptor, 7 > STATE_DESCRIPTORS
DoIPAddress m_routedClientAddress
bool m_isOpen
DoIPCloseReason m_closeReason = DoIPCloseReason::None
const StateDescriptor * m_state = nullptr
TimerManager< ConnectionTimers > m_timerManager
uint8_t m_aliveCheckRetry {0}
uint8_t m_aliveCheckRetryCount {DOIP_ALIVE_CHECK_RETRIES}
std::chrono::milliseconds m_initialInactivityTimeout {times::server::InitialInactivityTimeout}
std::chrono::milliseconds m_generalInactivityTimeout {times::server::GeneralInactivityTimeout}
std::chrono::milliseconds m_aliveCheckTimeout {times::server::AliveCheckResponseTimeout}
std::chrono::milliseconds m_downstreamResponseTimeout {10s}
Detailed Description
Definition at line 25 of file DoIPConnection.h.
Constructor & Destructor Documentation
DoIPConnection()
doip::DoIPConnection::DoIPConnection (int tcpSocket, UniqueServerModelPtr model)
Definition at line 11 of file DoIPConnection.cpp.
Member Function Documentation
closeConnection()
void doip::DoIPConnection::closeConnection (DoIPCloseReason reason) override virtual
Close the TCP connection.
Parameters
reason Why the connection is being closed
Implements doip::IConnectionContext.
Definition at line 130 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::closeConnection(), LOG_DOIP_DEBUG, LOG_DOIP_INFO, and fmt::streamed().
getClientAddress()
DoIPAddress doip::DoIPConnection::getClientAddress () const override virtual
Get the currently client (active source) address.
Returns
The client (active source) address, or 0 if no routing is active
Implements doip::IConnectionContext.
Definition at line 151 of file DoIPConnection.cpp.
getServerAddress()
DoIPAddress doip::DoIPConnection::getServerAddress () const override virtual
Get the server's logical address.
Returns
The server's DoIP logical address
Implements doip::IConnectionContext.
Definition at line 147 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::m_serverModel.
hasDownstreamHandler()
bool doip::DoIPConnection::hasDownstreamHandler () const override virtual
Check if downstream forwarding is available.
Returns
true if the server model has a downstream handler configured
Implements doip::IConnectionContext.
Definition at line 181 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::m_serverModel.
isSocketActive()
bool doip::DoIPConnection::isSocketActive () inline
Definition at line 34 of file DoIPConnection.h.
notifyConnectionClosed()
void doip::DoIPConnection::notifyConnectionClosed (DoIPCloseReason reason) override virtual
Notify application that connection is closing.
Parameters
reason Why the connection is closing
Implements doip::IConnectionContext.
Definition at line 168 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::m_serverModel.
notifyDiagnosticAckSent()
void doip::DoIPConnection::notifyDiagnosticAckSent (DoIPDiagnosticAck ack) override virtual
Notify application that diagnostic ACK/NACK was sent.
Parameters
ack The ACK/NACK that was sent
Implements doip::IConnectionContext.
Definition at line 175 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::m_serverModel.
notifyDiagnosticMessage()
DoIPDiagnosticAck doip::DoIPConnection::notifyDiagnosticMessage (const DoIPMessage & msg) override virtual
Handle an incoming diagnostic message (application callback)
Parameters
msg The diagnostic message received
Returns
std::nullopt for ACK, or NACK code
Implements doip::IConnectionContext.
Definition at line 159 of file DoIPConnection.cpp.
References doip::DoIPDefaultConnection::m_serverModel.
receiveFixedNumberOfBytesFromTCP()
size_t doip::DoIPConnection::receiveFixedNumberOfBytesFromTCP (uint8_t * receivedData, size_t payloadLength)
Receive exactly payloadLength bytes from the TCP stream and put them into receivedData.
The method blocks until receivedData bytes are received or the socket is closed.
The parameter receivedData needs to point to a readily allocated array with at least payloadLength items.
Returns
number of bytes received
Definition at line 85 of file DoIPConnection.cpp.
Referenced by receiveTcpMessage().
receiveTcpMessage()
int doip::DoIPConnection::receiveTcpMessage ()
Definition at line 29 of file DoIPConnection.cpp.
References doip::DOIP_HEADER_SIZE, doip::DoIPDefaultConnection::handleMessage2(), LOG_DOIP_DEBUG, LOG_DOIP_ERROR, LOG_DOIP_INFO, receiveFixedNumberOfBytesFromTCP(), fmt::streamed(), and doip::DoIPMessage::tryParseHeader().
sendDiagnosticAck()
void doip::DoIPConnection::sendDiagnosticAck (const DoIPAddress & sourceAddress)
sendDiagnosticNegativeAck()
void doip::DoIPConnection::sendDiagnosticNegativeAck (const DoIPAddress & sourceAddress, DoIPNegativeDiagnosticAck ackCode)
sendDiagnosticPayload()
void doip::DoIPConnection::sendDiagnosticPayload (const DoIPAddress & sourceAddress, const ByteArray & payload)
sendProtocolMessage()
ssize_t doip::DoIPConnection::sendProtocolMessage (const DoIPMessage & msg) override virtual
Send a DoIP protocol message to the client.
Parameters
msg The DoIP message to send
Implements doip::IConnectionContext.
Definition at line 120 of file DoIPConnection.cpp.
References doip::DoIPMessage::data(), LOG_DOIP_ERROR, LOG_DOIP_INFO, doip::DoIPMessage::size(), and fmt::streamed().
setClientAddress()
void doip::DoIPConnection::setClientAddress (const DoIPAddress & address) override virtual
Set the client (active source) address after routing activation.
Parameters
address The client's source address
Implements doip::IConnectionContext.
Definition at line 155 of file DoIPConnection.cpp.
triggerDisconnection()
void doip::DoIPConnection::triggerDisconnection ()
Definition at line 102 of file DoIPConnection.cpp.
References LOG_DOIP_INFO.
The documentation for this class was generated from the following files:
inc/DoIPConnection.h
src/DoIPConnection.cpp