libdoip: fmt Namespace Reference
fmt Namespace Reference
Classes
struct streamed_t
Functions
template<typename T >
streamed_t< T > streamed (const T &v)
template<typename OStream , typename T >
OStream & operator<< (OStream &os, const streamed_t< T > &s)
template<typename OStream , typename T >
OStream & operator<< (OStream &os, const streamed_t< std::optional< T >> &s)
Function Documentation
operator<<() [1/2]
template<typename OStream , typename T > OStream& fmt::operator<< (OStream & os, const streamed_t< std::optional< T >> & s)
Definition at line 34 of file Logger.h.
operator<<() [2/2]
template<typename OStream , typename T > OStream& fmt::operator<< (OStream & os, const streamed_t< T > & s)
Definition at line 27 of file Logger.h.
References fmt::streamed_t< T >::value.
streamed()
template<typename T > streamed_t<T> fmt::streamed (const T & v)
Definition at line 24 of file Logger.h.
Referenced by doip::DoIPConnection::closeConnection(), doip::DoIPDefaultConnection::closeConnection(), doip::DoIPDefaultConnection::handleRoutingActivated(), doip::DoIPDefaultConnection::handleTimeout(), doip::DoIPDefaultConnection::handleWaitAliveCheckResponse(), doip::DoIPDefaultConnection::receiveDownstreamResponse(), doip::DoIPClient::receiveMessage(), doip::DoIPConnection::receiveTcpMessage(), doip::DoIPClient::receiveUdpMessage(), doip::DoIPClient::receiveVehicleAnnouncement(), doip::DoIPDefaultConnection::restartStateTimer(), doip::DoIPClient::sendAliveCheckResponse(), doip::DoIPClient::sendDiagnosticMessage(), doip::DoIPConnection::sendProtocolMessage(), doip::DoIPDefaultConnection::sendProtocolMessage(), doip::DoIPClient::sendRoutingActivationRequest(), doip::DoIPDefaultConnection::startStateTimer(), and doip::DoIPDefaultConnection::transitionTo().