libdoip: doip::DoIPAddress Struct Reference
doip::DoIPAddress Struct Reference
Represents a 16-bit DoIP address consisting of high and low significant bytes.
#include <DoIPAddress.h>
Public Member Functions
constexpr DoIPAddress (uint8_t hsb=0, uint8_t lsb=0)
Constructs an DoIPAddress with specified high and low significant bytes.
constexpr DoIPAddress (const uint8_t *data, size_t offset=0)
Constructs an DoIPAddress from a byte array starting at the specified offset.
uint8_t lsb () const
Gets the low significant byte of the address.
uint8_t hsb () const
Gets the high significant byteconst DoIPAddress& sa of the address.
uint16_t toUint16 () const
Converts the address to a 16-bit unsigned integer.
const uint8_t * data () const
Gets a pointer to the internal byte array.
constexpr size_t size () const
Size of the address in bytes.
void update (uint8_t hsb, uint8_t lsb)
Updates the address with new high and low significant bytes.
void update (uint16_t hsblsb)
void update (const uint8_t *data, size_t offset=0)
Updates the address from a byte array starting at the specified offset.
ByteArray & appendTo (ByteArray &bytes) const
Appends this address to the given byte array.
bool operator== (const DoIPAddress &other) const
Compares two DoIPAddress objects for equality.
bool operator!= (const DoIPAddress &other) const
Compares two DoIPAddress objects for inequality.
bool isValidSourceAddress ()
Check if source address is valid.
Static Public Member Functions
static bool isValidSourceAddress (const uint8_t *data, size_t offset=0)
Check if source address is valid.
Static Public Attributes
static constexpr uint16_t MIN_SOURCE_ADDRESS = 0xE000
static constexpr uint16_t MAX_SOURCE_ADDRESS = 0xE3FF
static const DoIPAddress ZeroAddress = DoIPAddress()
Constant for a DoIP zero address (0x0000).
Detailed Description
Represents a 16-bit DoIP address consisting of high and low significant bytes.
This structure encapsulates a 16-bit address used in DoIP (Diagnostic over Internet Protocol) communication. The address is stored as two separate bytes (HSB and LSB) and provides convenient methods for construction, access, and manipulation.
Note
The address follows big-endian byte ordering (HSB first, then LSB).
Definition at line 27 of file DoIPAddress.h.
Constructor & Destructor Documentation
DoIPAddress() [1/2]
constexpr doip::DoIPAddress::DoIPAddress (uint8_t hsb = 0, uint8_t lsb = 0) inline explicit constexpr
Constructs an DoIPAddress with specified high and low significant bytes.
Parameters
hsb High significant byte (default: 0)
lsb Low significant byte (default: 0)
Definition at line 34 of file DoIPAddress.h.
References hsb(), and lsb().
DoIPAddress() [2/2]
constexpr doip::DoIPAddress::DoIPAddress (const uint8_t * data, size_t offset = 0) inline explicit constexpr
Constructs an DoIPAddress from a byte array starting at the specified offset.
This constructor reads two consecutive bytes from the provided data array, starting at the given offset. The first byte becomes the HSB and the second byte becomes the LSB.
Parameters
data Pointer to the byte array containing address data
offset Starting offset in the data array (default: 0)
Note
If data is nullptr, the address is initialized to {0, 0}
Warning
No bounds checking is performed on the data array
Definition at line 49 of file DoIPAddress.h.
Member Function Documentation
appendTo()
ByteArray& doip::DoIPAddress::appendTo (ByteArray & bytes) const inline
Appends this address to the given byte array.
Parameters
bytes the byte array to append to
Returns
ByteArray& the modified byte array
Definition at line 141 of file DoIPAddress.h.
Referenced by doip::message::makeDiagnosticMessage(), doip::message::makeDiagnosticNegativeResponse(), doip::message::makeDiagnosticPositiveResponse(), doip::message::makeRoutingActivationResponse(), and doip::DoIPDefaultConnection::sendRoutingActivationResponse().
data()
const uint8_t* doip::DoIPAddress::data () const inline
Gets a pointer to the internal byte array.
This method provides direct access to the underlying byte storage. The returned pointer points to a 2-byte array where:
data()[0] contains the HSB
data()[1] contains the LSB
Returns
Const pointer to the internal 2-byte array
Definition at line 90 of file DoIPAddress.h.
hsb()
uint8_t doip::DoIPAddress::hsb () const inline
Gets the high significant byteconst DoIPAddress& sa of the address.
Returns
The high significant byte (HSB) as uint8_t
Definition at line 68 of file DoIPAddress.h.
Referenced by DoIPAddress().
isValidSourceAddress() [1/2]
bool doip::DoIPAddress::isValidSourceAddress () inline
Check if source address is valid.
Returns
true the source address is valid
false the source address is NOT valid
Definition at line 179 of file DoIPAddress.h.
isValidSourceAddress() [2/2]
static bool doip::DoIPAddress::isValidSourceAddress (const uint8_t * data, size_t offset = 0) inline static
Check if source address is valid.
Parameters
data the data array containing the address
offset the offset in the data array where the address starts
Returns
true the source address is valid
false the source address is NOT valid
Definition at line 190 of file DoIPAddress.h.
lsb()
uint8_t doip::DoIPAddress::lsb () const inline
Gets the low significant byte of the address.
Returns
The low significant byte (LSB) as uint8_t
Definition at line 61 of file DoIPAddress.h.
Referenced by DoIPAddress().
operator!=()
bool doip::DoIPAddress::operator!= (const DoIPAddress & other) const inline
Compares two DoIPAddress objects for inequality.
Two addresses are considered unequal if either their high significant bytes or low significant bytes differ.
Parameters
other The DoIPAddress object to compare with
Returns
true if the addresses are not equal, false otherwise
Definition at line 169 of file DoIPAddress.h.
operator==()
bool doip::DoIPAddress::operator== (const DoIPAddress & other) const inline
Compares two DoIPAddress objects for equality.
Two addresses are considered equal if both their high significant bytes and low significant bytes are identical.
Parameters
other The DoIPAddress object to compare with
Returns
true if both addresses are equal, false otherwise
Definition at line 156 of file DoIPAddress.h.
References toUint16().
size()
constexpr size_t doip::DoIPAddress::size () const inline constexpr
Size of the address in bytes.
Returns
constexpr size_t the address size
Definition at line 97 of file DoIPAddress.h.
References doip::DOIP_ADDRESS_SIZE.
Referenced by doip::message::makeDiagnosticMessage(), doip::message::makeDiagnosticNegativeResponse(), doip::message::makeDiagnosticPositiveResponse(), doip::message::makeRoutingActivationRequest(), doip::message::makeRoutingActivationResponse(), and doip::message::makeVehicleIdentificationResponse().
toUint16()
uint16_t doip::DoIPAddress::toUint16 () const inline
Converts the address to a 16-bit unsigned integer.
The conversion follows big-endian byte ordering where the HSB forms the upper 8 bits and the LSB forms the lower 8 bits.
Returns
The address as a 16-bit unsigned integer in host byte order
Definition at line 78 of file DoIPAddress.h.
Referenced by doip::message::makeAliveCheckResponse(), doip::message::makeRoutingActivationRequest(), doip::message::makeVehicleIdentificationResponse(), doip::operator<<(), operator==(), and doip::DoIPDefaultConnection::sendRoutingActivationResponse().
update() [1/3]
void doip::DoIPAddress::update (const uint8_t * data, size_t offset = 0) inline
Updates the address from a byte array starting at the specified offset.
This method reads two consecutive bytes from the provided data array, starting at the given offset. The first byte becomes the HSB and the second byte becomes the LSB, overwriting the current address values.
Parameters
data Pointer to the byte array containing new address data
offset Starting offset in the data array (default: 0)
Warning
No bounds checking is performed on the data array. Ensure that data[offset] and data[offset+1] are valid memory locations.
No null pointer checking is performed. Ensure data is not nullptr.
Definition at line 128 of file DoIPAddress.h.
update() [2/3]
void doip::DoIPAddress::update (uint16_t hsblsb) inline
Definition at line 110 of file DoIPAddress.h.
update() [3/3]
void doip::DoIPAddress::update (uint8_t hsb, uint8_t lsb) inline
Updates the address with new high and low significant bytes.
Parameters
hsb New high significant byte
lsb New low significant byte
Definition at line 105 of file DoIPAddress.h.
Referenced by doip::DoIPServer::setLogicalGatewayAddress().
Member Data Documentation
MAX_SOURCE_ADDRESS
constexpr uint16_t doip::DoIPAddress::MAX_SOURCE_ADDRESS = 0xE3FF static constexpr
Definition at line 198 of file DoIPAddress.h.
MIN_SOURCE_ADDRESS
constexpr uint16_t doip::DoIPAddress::MIN_SOURCE_ADDRESS = 0xE000 static constexpr
Definition at line 197 of file DoIPAddress.h.
ZeroAddress
const DoIPAddress doip::DoIPAddress::ZeroAddress = DoIPAddress() inline static
Constant for a DoIP zero address (0x0000).
Definition at line 203 of file DoIPAddress.h.
The documentation for this struct was generated from the following file:
inc/DoIPAddress.h